language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
before_install:
  - pip install git+https://github.com/PeterJCLaw/ranker.git@python3-only
  - pip install git+https://github.com/PeterJCLaw/srcomp.git@python3-only
install: python setup.py install
script: python setup.py nosetests
