language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
matrix:
  allow_failures:
    - python: "3.9-dev"
before_install:
  - pip install -U pip setuptools
  - pip install git+https://github.com/PeterJCLaw/srcomp.git
  # Force Jinja2 to a version which supports Python 3.5
  - pip install 'Jinja2<3'
install: python setup.py install
script:
  - ./run-tests
  # Deliberately after running the real tests so that we can't accidentally
  # depend on it
  - pip install -r script/linting/requirements.txt
  - script/linting/lint
  - pip install -r script/typing/requirements.txt
  - script/typing/check
