language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
before_install:
  - pip install git+https://github.com/PeterJCLaw/ranker.git@league-ranker
  - pip install git+git://git.srobo.org/comp/srcomp.git
install: python setup.py install
script: python setup.py nosetests
